
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcrqkvrmamefgkxvkxoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcnFrdnJtYW1lZmdreHZreG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjc3MDgsImV4cCI6MjA1NjgwMzcwOH0.Tc9e1ouEzvKU6KOXiqiN0qoro7Z7sC7NQg-ehieosVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Tests the connection to Supabase
 * @returns An object with the status of the connection test
 */
export async function testSupabaseConnection() {
  try {
    // Simple query to test connection
    const { data, error, status } = await supabase
      .from("rec_centers")
      .select("id")
      .limit(1);
    
    if (error) {
      console.error("Supabase connection test failed:", error);
      return {
        success: false,
        status,
        message: error.message,
        error
      };
    }
    
    return {
      success: true,
      status,
      message: "Connected successfully",
      data
    };
  } catch (err) {
    console.error("Unexpected error during Supabase connection test:", err);
    const errorMessage = err instanceof Error ? err.message : String(err);
    
    return {
      success: false,
      status: 500,
      message: errorMessage,
      error: err
    };
  }
}

/**
 * Gets debug information about the Supabase configuration
 * @returns Debug information about the Supabase configuration
 */
export function getSupabaseDebugInfo() {
  return {
    url: SUPABASE_URL,
    keyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 10) + "...",
    localStorageAvailable: typeof localStorage !== 'undefined',
    supabaseClientInitialized: !!supabase,
    // Remove the protected 'rest' property access and replace with version info
    clientVersion: "@supabase/supabase-js"
  };
}
