
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcrqkvrmamefgkxvkxoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcnFrdnJtYW1lZmdreHZreG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjc3MDgsImV4cCI6MjA1NjgwMzcwOH0.Tc9e1ouEzvKU6KOXiqiN0qoro7Z7sC7NQg-ehieosVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : null,
  },
  global: {
    headers: {
      'x-client-info': 'lovable-recreation-centers-app'
    },
  },
  db: {
    schema: 'public',
  }
});

// Function to test the connection to Supabase
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('rec_centers').select('count(*)', { count: 'exact', head: true });
    
    if (error) {
      console.error('Supabase connection test failed:', error);
      return { success: false, error };
    }
    
    console.log('Supabase connection test successful:', data);
    return { success: true, data };
  } catch (err) {
    console.error('Unexpected error testing Supabase connection:', err);
    return { success: false, error: err };
  }
};
